mysql -u root -p test

drop database projeto_final;

create database projeto_final;

exit;

mysql -u root -p projeto_final

CREATE TABLE UF (
	SIGLA VARCHAR(2) PRIMARY KEY NOT NULL,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE MUNICIPIO (
	COD_TSE INT(8) PRIMARY KEY NOT NULL, 
	SIGLA_UF VARCHAR(2) NOT NULL, 
	NOME VARCHAR(100) NOT NULL, 
	CONSTRAINT FK_MUNICIPIO_UF
		FOREIGN KEY (SIGLA_UF) REFERENCES UF(SIGLA)
);

CREATE TABLE PARTIDO_POLITICO (
	NUMERO INT(2) PRIMARY KEY NOT NULL,
	SIGLA VARCHAR(10) NOT NULL,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE GRAU_INSTRUCAO (
	COD INT(1) PRIMARY KEY NOT NULL,
	DESCRICAO VARCHAR(30) NOT NULL
);

CREATE TABLE NACIONALIDADE (
	COD INT(2) PRIMARY KEY NOT NULL,
	DESCRICAO VARCHAR(30) NOT NULL
);

CREATE TABLE OCUPACAO (
	COD INT(5) PRIMARY KEY NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE CANDIDATO (
	CPF BIGINT(11) PRIMARY KEY NOT NULL,
	COD_TSE_MUNIC_NASC INT(8) NOT NULL,
	COD_NACIONALIDADE INT(2) NOT NULL,
	COD_OCUPACAO INT(5) NOT NULL,
	COD_GRAU_INST INT(1) NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	NRO_TITULO BIGINT(12) NOT NULL,
	EMAIL VARCHAR(100),
	SEXO VARCHAR(30) NOT NULL,
	ESTADO_CIVIL VARCHAR(20) NOT NULL,
	CONSTRAINT FK_CANDIDATO_MUNIC_NASC
		FOREIGN KEY (COD_TSE_MUNIC_NASC) REFERENCES MUNICIPIO(COD_TSE),
	CONSTRAINT FK_CANDIDATO_NACIONALIDADE
		FOREIGN KEY (COD_NACIONALIDADE) REFERENCES NACIONALIDADE(COD),
	CONSTRAINT FK_CANDIDATO_OCUPACAO
		FOREIGN KEY (COD_OCUPACAO) REFERENCES OCUPACAO(COD),
	CONSTRAINT FK_CANDIDATO_GRAU_INST
		FOREIGN KEY (COD_GRAU_INST) REFERENCES GRAU_INSTRUCAO(COD)
);

CREATE TABLE CANDIDATURA (	
	CPF_CANDIDATO BIGINT(11) NOT NULL,
	ANO_ELEICAO INT(4) NOT NULL, 
	NUMERO_PARTIDO INT(2) NOT NULL,
	COD_TSE_MUNIC_ELEICAO INT(8) NOT NULL,
	NUMERO_URNA INT(5) NOT NULL,
	NOME_URNA VARCHAR(100) NOT NULL,
	SITUACAO VARCHAR(30) NOT NULL,
	CARGO VARCHAR(20) NOT NULL,
	SITUACAO_ELEICAO VARCHAR(30) NOT NULL,
	SE_SEGUNDO_TURNO INT(1) NOT NULL,
	CONSTRAINT PK_CANDIDATURA
		PRIMARY KEY (CPF_CANDIDATO, ANO_ELEICAO),
	CONSTRAINT FK_CANDIDATURA_CANDIDATO
		FOREIGN KEY (CPF_CANDIDATO) REFERENCES CANDIDATO(CPF),
	CONSTRAINT FK_CANDIDATURA_PARTIDO
		FOREIGN KEY (NUMERO_PARTIDO) REFERENCES PARTIDO_POLITICO(NUMERO),
	CONSTRAINT FK_CANDIDATURA_MUNICIPIO
		FOREIGN KEY (COD_TSE_MUNIC_ELEICAO) REFERENCES MUNICIPIO(COD_TSE)
);