DELIMITER //
CREATE TRIGGER validar_idade
BEFORE INSERT on CANDIDATURA FOR EACH ROW
BEGIN
	DECLARE DT_NASC DATE;
	DECLARE MSG VARCHAR(255);

	SELECT c.DT_NASCIMENTO
	INTO DT_NASC
	FROM CANDIDATO c
	WHERE c.CPF = New.CPF_CANDIDATO;	
	
	CASE
		WHEN New.CARGO = 'PREFEITO'
		AND DATEDIFF(concat(New.ANO_ELEICAO, '-10-01'), DT_NASC) < 7665
		THEN
			SET MSG = "ERRO: Candidato a prefeito precisa possuir 21 anos.";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
		ELSE BEGIN END; 
	END CASE;
END;//