INSERT INTO MUNICIPIO(COD_TSE, SIGLA_UF, NOME) values (10375, 'PI', 'Bom Jesus');
INSERT INTO NACIONALIDADE(COD, DESCRICAO) values (1, 'Brasileiro Nato');
INSERT INTO OCUPACAO(COD, DESCRICAO) values (1, 'Servidor Público');
INSERT INTO GRAU_INSTRUCAO(COD, DESCRICAO) values (1, 'Superior Completo');
INSERT INTO PARTIDO_POLITICO(NUMERO, SIGLA, NOME) values (22, 'PPP', 'Partido');

INSERT INTO CANDIDATO
	(CPF, COD_TSE_MUNIC_NASC, COD_NACIONALIDADE, COD_OCUPACAO, COD_GRAU_INST, NOME,	DT_NASCIMENTO, NRO_TITULO, EMAIL, SEXO, ESTADO_CIVIL)
VALUES
	(13911893450, 10375, 1, 1, 1, 'Welder Luz', '1988-03-25', 123456, 'wweellddeerr@gmail.com', 'MASCULINO', 'CASADO');
	
INSERT INTO CANDIDATURA (CPF_CANDIDATO, ANO_ELEICAO, NUMERO_PARTIDO, COD_TSE_MUNIC_ELEICAO,	NUMERO_URNA, NOME_URNA,	SITUACAO, CARGO, SITUACAO_ELEICAO, SE_SEGUNDO_TURNO)
VALUES (13911893450, 2008, 22, 10375, 22222, 'Xavier Neto', 'DEFERIDO', 'PREFEITO', 'ELEITO', 0);