INSERT INTO MUNICIPIO(COD_TSE, SIGLA_UF, NOME) values (1, 'PI', 'Bom Jesus');
INSERT INTO NACIONALIDADE(COD, DESCRICAO) values (1, 'Brasileiro Nato');
INSERT INTO OCUPACAO(COD, DESCRICAO) values (1, 'Servidor Público');
INSERT INTO GRAU_INSTRUCAO(COD, DESCRICAO) values (1, 'Superior Completo');

INSERT INTO CANDIDATO
	(CPF, COD_TSE_MUNIC_NASC, COD_NACIONALIDADE, COD_OCUPACAO, COD_GRAU_INST, NOME,	DT_NASCIMENTO, NRO_TITULO, EMAIL, SEXO, ESTADO_CIVIL)
VALUES
	(03372241371, 1, 1, 1, 1, 'Welder Luz', '1991-12-31', 123456, 'wweellddeerr@gmail.com', 'MASCULINO', 'CASADO');
	
INSERT INTO CANDIDATURA
	(CPF_CANDIDATO BIGINT(11) NOT NULL,
	ANO_ELEICAO INT(4) NOT NULL, 
	NUMERO_PARTIDO INT(2) NOT NULL,
	COD_TSE_MUNIC_ELEICAO INT(8) NOT NULL,
	NUMERO_URNA INT(5) NOT NULL,
	NOME_URNA VARCHAR(100) NOT NULL,
	SITUACAO VARCHAR(50) NOT NULL,
	CARGO VARCHAR(20) NOT NULL,
	SITUACAO_ELEICAO VARCHAR(30) NOT NULL,
	SE_SEGUNDO_TURNO)
VALUES
	()